#!/usr/bin/env bash
# A script that transfers a file from our client to a server

len=$#

if [ $len -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
scp -o StrictHostKeyChecking=no $1 $3@$2:$4
