#!/usr/bin/env bash
# A script that configures a new Ubuntu machine with Nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo bash -c 'cat > /var/www/html/index.html << EOF
Hello World!
EOF'
sudo /etc/init.d/nginx start
