#!/usr/bin/env bash
# A script that configures a new Ubuntu machine with Nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '/^\s*server_name _;/a \ \ \ \ \ \ \ \ return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4\$request_uri;' /etc/nginx/sites-enabled/default
sudo service nginx reload
