#!/usr/bin/env bash
# A script that configures a new Ubuntu machine with Nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
sudo touch /var/www/html/index.html
sudo bash -c 'cat > /var/www/html/index.html << EOF
Hello World!
EOF'

sudo sed -i '/^\s*location\s\/\s{/a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ rewrite ^/redirect_me(.*)$ https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default
sudo touch /var/www/html/error404.html
sudo bash -c "cat > /var/www/html/error404.html << EOF
Ceci n'est pas une page
EOF"
sudo sed -i '/^\s*location\s\/\s{/a \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ error_page\ 404\ /error404.html;' /etc/nginx/sites-enabled/default
sudo service nginx reload
