#!/usr/bin/env bash
# A script that configures a new Ubuntu machine with Nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo bash -c 'cat > /var/www/html/index.html << EOF
Hello World!
EOF'
sudo /etc/init.d/nginx start
sudo touch /var/www/html/error404.html
sudo bash -c "cat > /var/www/html/error404.html << EOF
Ceci n'est pas une page
EOF"
error_page="       server_name _;\n\n         error_page 404 /error404.html\n"
sudo sed -i "s/       server_name _;/$error_page/g" /etc/nginx/sites-enabled/default
sudo /etc/init.d/nginx reload
