#!/usr/bin/env bash
# A script that configures a new Ubuntu machine with Nginx installation

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "/\s*types_hash_max_size\s2048;/a \ \ \ \ \ \ \ \ add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx reload
shellcheck -e SC2154 0-custom_http_response_header
