#!/usr/bin/env bash
# A script that configures a new Ubuntu machine with Nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
sudo bash -c 'cat > /var/www/html/index.html << EOF
Hello World!
EOF'
sudo sed -i "/^\s*server_name _;/a \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx reload
shellcheck -e SC2154 0-custom_http_response_header
