#!/usr/bin/env bash
# Fixes issues with Nginx installation

# Make changes to configuration files
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo service nginx restart
