#!/usr/bin/env bash
# This script Indefinitely writes I am alive! to the file /tmp/my_process and
#+ pauses for 2 seconds in between

file="/tmp/my_process"
touch "$file"

n=1

while [ $n -gt 0 ]
do
    echo "I am alive!"
    sleep 2
    n=$((n + 1))
done
