#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd

filename="/etc/passwd"

while IFS=: read -r user pass uid gid gecos home shell
do
    echo "The user $user is part of the $gid gang, lives in\
 $home and rides $shell. $uid's place is protected\
 by the passcode $pass, more info about the user here: $gecos"
done < $filename
