#!/usr/bin/env bash
# This script displays the content of the current directory in list format
#+ where only the part of the name after the first dash is displayed

for line in *
do
    echo "$line" | cut -d "-" -f 2-
done
