#!/usr/bin/env bash
# run the whoami command under the user passed as an argument
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 700 /etc/nginx/nginx.conf
pkill -f apache2
sudo -u nginx service nginx start
