#!/usr/bin/env bash
# run the whoami command under the user passed as an argument
sudo sed -i 's/80/8080/g' /etc/nginx/conf.d/default.conf
sudo chown -R nginx:nginx /etc/nginx/ /var/log/nginx/ /var/cache/nginx/
pkill -f apache2
sudo -u nginx service nginx start
